export enum EnvEnum {
  TYPEORM_CONNECTION = "TYPEORM_CONNECTION",
  TYPEORM_HOST = "TYPEORM_HOST",
  TYPEORM_USERNAME = "TYPEORM_USERNAME",
  TYPEORM_PASSWORD = "TYPEORM_PASSWORD",
  TYPEORM_DATABASE = "TYPEORM_DATABASE",
  TYPEORM_SYNCHRONIZE = "TYPEORM_SYNCHRONIZE",
  TYPEORM_PORT = "TYPEORM_PORT",
}
