version: '3.8'
services:
  postgres-test:
    container_name: ottonova-db-test
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ottonova-test
    ports:
      - 5432:5432
