version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ottonova
    ports:
      - 5432:5432
