FROM node:18-alpine as build

WORKDIR /app

ADD package.json /app/package.json

RUN npm install --legacy-peer-deps

ADD . /app

RUN npx nx build front 

# prepare nginx
FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY apps/front/nginx.conf /etc/nginx/conf.d/
COPY --from=build app/dist/apps/front /usr/share/nginx/html 

# start nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]